name: Cypress Tests

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 1 * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
