name: Cypress Tests

on: [push, pull]

on:
  schedule:
    - cron:  '*/5 5-20 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start